// Code generated by genproviders from providers.yaml. DO NOT EDIT.

package config

// providerDefaults is the metadata table for known providers, indexed by
// user-facing provider name. It is merged into Config.Providers by
// applyDefaults to fill in missing fields and to set the runtime-only
// RequireBaseURL and SupportsCountTokens flags.
//
// Every provider is a first-class entry: there is no alias rewriting at
// load time.
var providerDefaults = map[string]Provider{
	"anthropic": {
		Behavior:            "anthropic",
		DefaultAPIKeyEnv:    "ANTHROPIC_API_KEY", // #nosec G101 -- env var name, not a credential
		RequireBaseURL:      true,
		SupportsCountTokens: true,
	},
	"custom": {
		Behavior:            "mix",
		RequireBaseURL:      true,
		SupportsCountTokens: false,
	},
	"go": {
		Behavior:            "mix",
		DefaultAPIKeyEnv:    "OPENCODE_API_KEY", // #nosec G101 -- env var name, not a credential
		RequireBaseURL:      true,
		SupportsCountTokens: false,
	},
	"mix": {
		Behavior:            "mix",
		RequireBaseURL:      true,
		SupportsCountTokens: false,
	},
	"nim": {
		Behavior:            "openai",
		DefaultBaseURL:      "https://integrate.api.nvidia.com/v1/chat/completions", // #nosec G101 -- URL, not a credential
		DefaultAPIKeyEnv:    "NVIDIA_NIM_API_KEY",                                   // #nosec G101 -- env var name, not a credential
		RequireBaseURL:      false,
		SupportsCountTokens: false,
	},
	"openai": {
		Behavior:            "openai",
		RequireBaseURL:      true,
		SupportsCountTokens: false,
	},
	"zen": {
		Behavior:            "mix",
		DefaultAPIKeyEnv:    "OPENCODE_API_KEY", // #nosec G101 -- env var name, not a credential
		RequireBaseURL:      true,
		SupportsCountTokens: false,
	},
}
