// Code generated by genproviders from providers.yaml. DO NOT EDIT.

package config

// KnownProviders lists the provider names accepted by the validator.
// This is a config-time validation surface — it includes aliases (zen, go,
// custom) that rewrite to mix at applyDefaults time.
var KnownProviders = map[string]struct{}{
	"anthropic": {},
	"custom":    {},
	"go":        {},
	"mix":       {},
	"nim":       {},
	"openai":    {},
	"zen":       {},
}

// knownProviderDefaults maps provider names to their default base_url and
// api_key_env values. Used by applyEntryDefaults to fill in missing fields
// before validation runs.
var knownProviderDefaults = map[string]modelDefaults{
	"anthropic": {
		APIKeyEnv: "ANTHROPIC_API_KEY", // #nosec G101 -- env var name, not a credential
	},
	"go": {
		APIKeyEnv: "OPENCODE_API_KEY", // #nosec G101 -- env var name, not a credential
	},
	"nim": {
		BaseURL:   "https://integrate.api.nvidia.com/v1/chat/completions", // #nosec G101 -- URL, not a credential
		APIKeyEnv: "NVIDIA_NIM_API_KEY",                                   // #nosec G101 -- env var name, not a credential
	},
	"zen": {
		APIKeyEnv: "OPENCODE_API_KEY", // #nosec G101 -- env var name, not a credential
	},
}

// requireBaseURL is the set of provider names that must have an explicit
// base_url after applyDefaults. (Providers with default_base_url are not
// included — they fill in their own.)
var requireBaseURL = map[string]struct{}{
	"anthropic": {},
	"custom":    {},
	"go":        {},
	"mix":       {},
	"openai":    {},
	"zen":       {},
}

// PresetProviders returns the provider names that have a default
// api_key_env, sorted alphabetically. Used by main.go's
// checkRequiredEnvVars to decide which providers to validate env vars for.
func PresetProviders() []string {
	return []string{
		"anthropic",
		"go",
		"nim",
		"zen",
	}
}

// applyEntryDefaults implements the two-phase rewrite pattern:
//
//	Phase A (pre-lookup):  aliases with no defaults entry rewrite first,
//	  so the defaults lookup sees the canonical name.
//	Phase B (post-lookup): aliases with defaults inherit their defaults
//	  before rewriting to the canonical adapter.
//
// custom → mix runs in Phase A (no defaults entry exists for "custom").
// zen → mix and go → mix run in Phase B (defaults must apply first so
// they inherit OPENCODE_API_KEY).
func applyEntryDefaults(m Model) Model {
	if m.OriginalProvider == "" {
		m.OriginalProvider = m.Provider
	}
	if m.Provider == "custom" {
		m.Provider = "mix"
	}
	d, ok := knownProviderDefaults[m.Provider]
	if !ok {
		return m
	}
	if m.BaseURL == "" {
		m.BaseURL = d.BaseURL
	}
	if m.APIKeyEnv == "" {
		m.APIKeyEnv = d.APIKeyEnv
	}
	if m.Provider == "go" {
		m.Provider = "mix"
	}
	if m.Provider == "zen" {
		m.Provider = "mix"
	}
	return m
}
