// Code generated by genproviders from providers.yaml. DO NOT EDIT.

package proxy

import (
	"log/slog"
	"time"
)

// NewDefaultRegistry returns a Registry wired with the default adapter set.
// streamTimeout and verboseErrors configure the underlying core adapters
// (OpenAICompatible, AnthropicCompatible, Mix). overrides lets callers
// swap any of the default adapters — used for "manual: true" providers
// that need hand-written logic.
func NewDefaultRegistry(
	logger *slog.Logger,
	streamTimeout time.Duration,
	verboseErrors bool,
	overrides map[string]Provider,
) *Registry {
	providers := map[string]Provider{
		"nim":       NewOpenAICompatibleAdapterWithTimeout(logger, streamTimeout),
		"openai":    NewOpenAICompatibleAdapterWithTimeout(logger, streamTimeout),
		"anthropic": NewAnthropicCompatibleAdapterWithTimeout(logger, verboseErrors, streamTimeout),
		"mix":       NewMixAdapter(logger, verboseErrors, streamTimeout),
	}
	for name, p := range overrides {
		providers[name] = p
	}
	return NewRegistry(providers)
}
