name: Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pfrack/review-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          custom_api_url: ${{ secrets.CUSTOM_API_URL }}
          custom_model: ${{ secrets.CUSTOM_MODEL }}
          custom_api_key: ${{ secrets.CUSTOM_API_KEY }}
          nim_api_key: ${{ secrets.CUSTOM_NIM_API_KEY }}
          mistral_api_key: ${{ secrets.CUSTOM_MISTRAL_API_KEY }}
