package envinject

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type shellConfig struct {
	lang string
	rc   string
}

var knownShells = map[string]shellConfig{
	"zsh":  {lang: "zsh", rc: ".zshrc"},
	"bash": {lang: "bash", rc: ".bashrc"},
	"fish": {lang: "fish", rc: filepath.Join(".config", "fish", "config.fish")},
}

const (
	startMarker = "# >>> freedius env >>>"
	endMarker   = "# <<< freedius env <<<"
)

func shellBlock(host string, port int, lang string) string {
	addr := fmt.Sprintf("http://%s:%d", host, port)
	switch lang {
	case "zsh", "bash":
		return fmt.Sprintf(`%s
# Auto-generated by freedius (Ctrl+S in Config tab).
# Remove everything between the markers to uninstall.
export ANTHROPIC_BASE_URL="%s"
export ANTHROPIC_API_KEY="freedius-dummy"
export ENABLE_TOOL_SEARCH="true"
export DISABLE_TELEMETRY="1"
export DISABLE_ERROR_REPORTING="1"
%s`, startMarker, addr, endMarker)
	case "fish":
		return fmt.Sprintf(`%s
# Auto-generated by freedius (Ctrl+S in Config tab).
# Remove everything between the markers to uninstall.
set -gx ANTHROPIC_BASE_URL "%s"
set -gx ANTHROPIC_API_KEY "freedius-dummy"
set -gx ENABLE_TOOL_SEARCH "true"
set -gx DISABLE_TELEMETRY "1"
set -gx DISABLE_ERROR_REPORTING "1"
%s`, startMarker, addr, endMarker)
	default:
		return ""
	}
}

// WriteShellRC appends (or replaces, when force is true) the freedius env block
// in the user's shell rc file for the shell identified by $SHELL. When dryRun
// is true the resulting file content is printed to stdout and the file is left
// untouched. The returned string is the rc file path that would be (or was) edited.
func WriteShellRC(
	homeDir string,
	shell string,
	host string,
	port int,
	force bool,
	dryRun bool,
) (string, error) {
	shell = filepath.Base(shell)
	cfg, ok := knownShells[shell]
	if !ok {
		return "", fmt.Errorf("unsupported shell %q: use zsh, bash, or fish", shell)
	}
	rcPath := filepath.Join(homeDir, cfg.rc)

	block := shellBlock(host, port, cfg.lang)
	if block == "" {
		return "", fmt.Errorf("unsupported shell %q: use zsh, bash, or fish", shell)
	}

	existing := ""
	// #nosec G304 -- path is the operator's own shell rc file
	if data, err := os.ReadFile(rcPath); err == nil {
		existing = string(data)
	}

	if strings.Contains(existing, startMarker) {
		if !force {
			return rcPath, fmt.Errorf("already installed in %s (use --force to replace)", rcPath)
		}
		// Remove existing marker block.
		startIdx := strings.Index(existing, startMarker)
		endIdx := strings.Index(existing, endMarker)
		if startIdx >= 0 && endIdx >= 0 {
			before := existing[:startIdx]
			after := existing[endIdx+len(endMarker):]
			existing = before + strings.TrimLeft(after, "\n")
		}
	}

	content := existing
	if content == "" {
		content = block + "\n"
	} else {
		if !strings.HasSuffix(content, "\n") {
			content += "\n"
		}
		content += block + "\n"
	}

	if dryRun {
		fmt.Print(content)
		return rcPath, nil
	}

	dir := filepath.Dir(rcPath)
	// #nosec G301 -- user-owned directory; group/other read keeps the rc file tooling-compatible
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", fmt.Errorf("create parent dir %s: %w", dir, err)
	}
	// #nosec G306,G703 -- user-owned rc file; rcPath is filepath.Join(homeDir, knownSafe) where homeDir is the operator's $HOME
	if err := os.WriteFile(rcPath, []byte(content), 0o644); err != nil {
		return "", fmt.Errorf("write %s: %w", rcPath, err)
	}
	return rcPath, nil
}
